### ISSUE TITLE
Working in H16

### ISSUE THREAD

**Issue by melMass** [ArthurYidi/Houdini-External-Editor#3]
Thanks a lot.
For anyone wondering this is still working.

This should be builtin to Houdini !! 🥇 

I have added a simple syntax highlighter for VEX in Visual Code: [vscode-vex](https://github.com/melMass/vscode-vex)

If you want to add VSCode to the list of choices, here is the command (on OSX):

    /usr/local/bin/code --wait

**Comment by melMass** [comment]
Better alternative (non blocking):

http://cgtoolbox.com/houdini-expression-editor/

**Comment by ArthurYidi** [comment]
great find, thanks!
